version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=research_db
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: